spring:
#  datasource:
#    url: jdbc:h2:mem:test
#    driver-class-name: org.h2.Driver
#    username: sa
#  h2:
#    console:
#      enabled: true
#      path: /h2  # Context path
#  datasource:
#    url: jdbc:h2:mem:CherryPick  # JDBC URL
#
  datasource:
    url: jdbc:mysql://localhost:3306/cherry_pick?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

