spring:
  jpa:
    hibernate:
      ddl-auto: update  # ??? ?? ??
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
    open-in-view: false
  profiles:
    include: database, security
#  security:
#    user:
#      name: user
#      password: 42c52c05-6171-4f0a-972b-861f25d1a091



