spring:
  h2:
    console:
      enabled: true
      path: /h2  # Context path
  datasource:
    url: jdbc:h2:mem:CherryPick  # JDBC URL
  jpa:
    hibernate:
      ddl-auto: create  # ??? ?? ??
    show-sql: true  # SQL ?? ??
  servlet:  # 이미지 로컬에 저장하기 위한 설정. S3 사용시 바꾸어야 함!
    multipart:
      location: /Users/gnidinger/Desktop/
      maxFileSize: 5MB
      maxRequestSize: 10MB
mail:
  address:
    admin: admin@gmail.com
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
