spring:
  jpa:
    hibernate:
      ddl-auto: update  # ??? ?? ??
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
    open-in-view: false
  profiles:
    include: database, security
#  security:
#    user:
#      name: user
#      password: 42c52c05-6171-4f0a-972b-861f25d1a091


  servlet:  # 이미지 로컬에 저장하기 위한 설정. S3 사용시 바꾸어야 함!
    multipart:
      location: /Users/gnidinger/Desktop/
      maxFileSize: 5MB
      maxRequestSize: 10MB
mail:
  address:
    admin: admin@gmail.com
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
