name: Client Auto Deploy after Push
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i -f
        working-directory: ./front
      - name: Generate Environment Variables File for Development
        run: |
          echo "REACT_APP_SERVICE_VERSION=$REACT_APP_SERVICE_VERSION" >> .env.development
          echo "REACT_APP_API_URL=$REACT_APP_API_URL" >> .env.development
        working-directory: ./front
        env:
          REACT_APP_SERVICE_VERSION: 0.0.18
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      - name: Build
        run: npm run build
        working-directory: ./front
      - name: SHOW AWS CLI VERSION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws --version
      - name: Sync Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            build s3://main-012-client \
            --delete
        working-directory: "./front"
